media:
  input: public
  output: /

content:
  - name: site
    label: Saidi sisu
    path: src/content/site.yaml
    type: file
    fields:

      # ── BÄNNER ──
      - name: banner
        label: Teadaanne
        type: object
        fields:
          - name: enabled
            label: Teadaanne aktiivne
            type: boolean
            description: "Lülita sisse, et kuvada kollane teadaanderiba lehe ülaosas."
          - name: text
            label: Teadaande tekst
            type: string
            description: "Tekst, mis kuvatakse teadaandes (emojid on lubatud)."
          - name: type
            label: Teadaande tüüp
            type: select
            default: warning
            options:
              values:
                - value: warning
                  label: Hoiatus
                - value: info
                  label: Info

      # ── PÄIS ──
      - name: header
        label: Päis
        type: object
        fields:
          - name: logo_title
            label: Logo pealkiri
            type: string
          - name: logo_subtitle
            label: Logo alapealkiri
            type: string
          - name: nav_links
            label: Navigatsiooni lingid
            type: object
            list: true
            fields:
              - name: label
                label: Tekst
                type: string
              - name: href
                label: "Ankur (#id)"
                type: string
          - name: phone
            label: "Telefon (tehniline, nt +3727319241)"
            type: string
          - name: phone_display
            label: "Telefon (kuvatav, nt 731 9241)"
            type: string
          - name: external_link
            label: Väline link
            type: object
            fields:
              - name: url
                label: URL
                type: string
              - name: label
                label: Tekst
                type: string

      # ── HERO SEKTSIOON ──
      - name: hero
        label: Hero sektsioon
        type: object
        fields:
          - name: title
            label: Pealkiri
            type: string
          - name: subtitle
            label: Alapealkiri
            type: string
          - name: background_image
            label: Taustapilt
            type: image
          - name: cta_text
            label: Nupu tekst
            type: string
          - name: cta_url
            label: Nupu link
            type: string

      # ── TEATISED ──
      - name: notices
        label: Teatised
        type: object
        list: true
        fields:
          - name: enabled
            label: Teatis aktiivne
            type: boolean
          - name: text
            label: Teatise tekst
            type: text
          - name: link
            label: "Link (valikuline)"
            type: object
            fields:
              - name: url
                label: URL
                type: string
              - name: label
                label: Lingi tekst
                type: string

      # ── LAHTIOLEKUAJAD ──
      - name: opening_hours
        label: Lahtiolekuajad
        type: object
        fields:
          - name: section_title
            label: Sektsiooni pealkiri
            type: string
          - name: schedule
            label: Graafik
            type: object
            list: true
            fields:
              - name: day
                label: "Päev (nt E, T, K)"
                type: string
              - name: time
                label: "Aeg (nt 8:00–16:00)"
                type: string
          - name: phone
            label: Lauatelefon
            type: string
          - name: mobile
            label: Mobiil
            type: string
          - name: map_embed_url
            label: Google Maps manustamise URL
            type: string
          - name: map_title
            label: Kaardi pealkiri (ekraanilugejatele)
            type: string

      # ── TÖÖTAJAD ──
      - name: staff
        label: Töötajad
        type: object
        fields:
          - name: section_title
            label: Sektsiooni pealkiri
            type: string
          - name: note
            label: Allmärkus
            type: text
          - name: members
            label: Töötajad
            type: object
            list: true
            fields:
              - name: name
                label: Nimi
                type: string
              - name: role
                label: Ametinimetus
                type: string
              - name: cabinet
                label: Kabineti number
                type: string
              - name: schedule
                label: Vastuvõtugraafik
                type: object
                list: true
                fields:
                  - name: day
                    label: Päev
                    type: string
                  - name: time
                    label: Kellaaeg
                    type: string

      # ── PATSIENDILE (AKORDION) ──
      - name: accordion_items
        label: Patsiendile sektsioon
        type: object
        fields:
          - name: section_title
            label: Sektsiooni pealkiri
            type: string
          - name: section_subtitle
            label: Sektsiooni alapealkiri
            type: string
          - name: items
            label: Patsiendile sektsioonid
            type: object
            list: true
            fields:
              - name: id
                label: "ID (unikaalne, nt vastuvott)"
                type: string
              - name: icon
                label: Ikoon
                type: select
                options:
                  values:
                    - value: Stethoscope
                      label: Stetoskoop
                    - value: CreditCard
                      label: Krediitkaart
                    - value: MessageSquare
                      label: Sõnumid
                    - value: UserPlus
                      label: Lisa kasutaja
                    - value: FileText
                      label: Dokument
              - name: title
                label: Pealkiri
                type: string
              - name: content
                label: Sisu
                type: rich-text
                description: "Saab kasutada pakskirja (**tekst**), linke ([tekst](url)), loendeid ja tabeleid."

      # ── KONTAKT ──
      - name: contact
        label: Kontaktinfo
        type: object
        fields:
          - name: section_title
            label: Sektsiooni pealkiri
            type: string
          - name: address
            label: Aadress
            type: string
          - name: cabinet
            label: Kabineti number
            type: string
          - name: phone
            label: Telefon
            type: string
          - name: mobile
            label: Mobiiltelefon
            type: string
          - name: email
            label: E-posti aadress
            type: string
          - name: external_links
            label: Välised lingid
            type: object
            list: true
            fields:
              - name: url
                label: URL
                type: string
              - name: label
                label: Lingi tekst
                type: string
          - name: insurance_note
            label: Kindlustusmärkus
            type: string

      # ── JALUS ──
      - name: footer
        label: Jalus
        type: object
        fields:
          - name: copyright_name
            label: Autoriõiguse omaniku nimi
            type: string
